pipeline {
    agent none
    stages {
        stage('INITIALIZE BUILD') {
            steps {
                script {
                    if ("${BUILD_NAME}") {
                        script {
                            currentBuild.displayName = "${BUILD_NAME}_${env.BUILD_NUMBER}"
                        }
                    }
                }
            }
        }
        stage('Check Out Git Code'){
            agent { node { label "${TEST_NODE}" } }
            steps {
                script {
                        def project_git_url = "${PROJECT_GIT_URL}"
                        echo "Cleaning Up the Workspcae ..."
                        cleanWs()
                        dir("python"){
                            downloadCode("${PROJECT_GIT_URL}", "${PROJECT_GIT_REFSPEC}")
                        }
                        stash includes: 'python/**', name: 'python'
                }
            }
        }
        stage('Execution'){
            agent { node { label "${TEST_NODE}" } }
            steps {
                script {

                    test_execution()
                }
            }
        }
        stage('Email'){
            agent { node { label "${TEST_NODE}" } }
            steps {
                script {
                    send_email_notification("First", "win10")
                }
            }
        }
    }
}

def downloadCode(git_url, git_refspec){
    echo "Git Repository: " + git_url
    checkout([$class: 'GitSCM',
    branches: [[name: 'FETCH_HEAD']],
    doGenerateSubmoduleConfigurations: false,
    extensions: [],
    submoduleCfg: [],
    userRemoteConfigs: [[credentialsId: "${USER_CREDENTIAL}",
                        refspec: git_refspec,
                        url: git_url]]
    ])
}

def test_execution(){
    echo "Executing Test ..."
    bat """
        set PYTHONPATH=%cd%
        python python/runner.py
        """
}

def send_email_notification(project, suffix){
    if("${SEND_EMAIL}".toBoolean()){
        echo "Sending email"
        junit "TestResultSummary-*.xml"
        echo "Build completed. currentBuild.result = ${currentBuild.result}"
        emailext body: '''${SCRIPT, template="email_notification_custom.template"}''',
        mimeType: 'text/html',
        subject: "[${project}]Job ${env.JOB_NAME}_${suffix} [Status:${currentBuild.currentResult}]",
        to: "${EMAIL_LIST}"
    }else{
        echo "Email sending skipped"
    }
}
